### ISSUE TITLE
TOKEN环境变量没起作用

### ISSUE THREAD

**Issue by kimmax603** [cmliu/CF-Workers-TEXT2KV#2]
烦请大佬检查
Workers环境部署，TOKEN变量的值，未起作用

**Comment by cmliu** [comment]
我又重新部署了一次, TOKEN变量是正常生效的啊

**Comment by kimmax603** [comment]
我重新部署了一个新的，是没问题的。
但是在原本的项目上更新代码，不知道为什么TOKEN环境变量就是不生效。
很奇怪，不过没事，重新部署用吧。
谢谢大佬
