### ISSUE TITLE
linux更新不成功

### ISSUE THREAD

**Issue by namjar** [cmliu/CF-Workers-TEXT2KV#6]
./update.sh result.csv
./update.sh ip.txt

都不行

我用的Macos

**Comment by cmliu** [comment]
我没有mac环境, 做不了这个测试, 不好意思, 之前有人提交过新的sh上来说我可以让mac使用的, 我没环境试所以也不知道行不行, 你更新一下试试?

**Comment by namjar** [comment]
我修改了，提交了，删除两个参数就可以了On Fri, Mar 29, 2024 at 1:49,             CMLiussss ***@***.***> wrote:
我没有mac环境, 做不了这个测试, 不好意思, 之前有人提交过新的sh上来说我可以让mac使用的, 我没环境试所以也不知道行不行, 你更新一下试试?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/cmliu/CF-Workers-TEXT2KV/issues/6#issuecomment-2025789508",
"url": "https://github.com/cmliu/CF-Workers-TEXT2KV/issues/6#issuecomment-2025789508",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
